package main

// Auto-generated catalog from programmercarl.com sidebar.

type catalogItem struct {
	Path  string
	Title string
}

type catalogSection struct {
	ID    string
	Label string
	Items []catalogItem
}

var catalogSections = []catalogSection{
	{ID: "perf", Label: "算法性能分析", Items: []catalogItem{
		{Path: "/前序/时间复杂度.html", Title: "时间复杂度分析"},
		{Path: "/前序/算法超时.html", Title: "算法为什么会超时"},
		{Path: "/前序/递归算法的时间复杂度.html", Title: "递归算法的时间复杂度"},
		{Path: "/前序/空间复杂度.html", Title: "空间复杂度分析"},
		{Path: "/前序/递归算法的时间与空间复杂度分析.html", Title: "递归算法的性能分析"},
		{Path: "/前序/内存消耗.html", Title: "代码的内存消耗"},
	}},
	{ID: "literacy", Label: "编程素养", Items: []catalogItem{
		{Path: "/前序/代码风格.html", Title: "代码风格"},
		{Path: "/前序/刷力扣用不用库函数.html", Title: "刷力扣用不用库函数？"},
		{Path: "/前序/力扣上的代码在本地编译运行.html", Title: "力扣上的代码在本地编译运行"},
		{Path: "/前序/ACM模式.html", Title: "注意核心代码模式和ACM模式"},
		{Path: "/前序/ACM模式如何构建二叉树.html", Title: "ACM模式如何构建二叉树"},
		{Path: "/前序/vim.html", Title: "人生苦短，我用VIM！"},
		{Path: "/前序/kvstore.html", Title: "手把手开发存储引擎"},
		{Path: "/前序/server.html", Title: "如何使用一台服务器"},
		{Path: "/前序/gitserver.html", Title: "如何搭建git私服"},
		{Path: "/前序/程序员写文档工具.html", Title: "程序员写文档工具"},
		{Path: "/前序/Java处理输入输出.html", Title: "Java处理输入输出"},
		{Path: "/前序/编程素养部分的吹毛求疵.html", Title: "编程素养：吹毛求疵"},
	}},
	{ID: "career", Label: "求职", Items: []catalogItem{
		{Path: "/前序/程序员简历.html", Title: "程序员的简历应该这么写"},
		{Path: "/前序/BAT级别技术面试流程和注意事项都在这里了.html", Title: "BAT级别技术面试流程和注意事项"},
	}},
	{ID: "lang", Label: "编程语言基础", Items: []catalogItem{
		{Path: "/qita/language.html", Title: "编程语言基础课"},
		{Path: "/ke/shejimoshi.html", Title: "设计模式编程课"},
		{Path: "/ke/cplus.html", Title: "C++基础课"},
		{Path: "/ke/java.html", Title: "Java基础课"},
		{Path: "/ke/python.html", Title: "Python基础课"},
		{Path: "/ke/go.html", Title: "Go基础课"},
		{Path: "/ke/js.html", Title: "Javascript基础课"},
		{Path: "/ke/stl.html", Title: "手写STL（C++）"},
		{Path: "/ke/kvcplus.html", Title: "kv存储-CPP"},
	}},
	{ID: "array", Label: "数组", Items: []catalogItem{
		{Path: "/数组理论基础.html", Title: "1. 数组理论基础"},
		{Path: "/0704.二分查找.html", Title: "2. 二分查找"},
		{Path: "/0027.移除元素.html", Title: "3. 移除元素"},
		{Path: "/0977.有序数组的平方.html", Title: "4. 有序数组的平方"},
		{Path: "/0209.长度最小的子数组.html", Title: "5. 长度最小的子数组"},
		{Path: "/0059.螺旋矩阵II.html", Title: "6. 螺旋矩阵II"},
		{Path: "/kamacoder/0058.区间和.html", Title: "7. 区间和"},
		{Path: "/kamacoder/0044.开发商购买土地.html", Title: "8. 开发商购买土地"},
		{Path: "/数组总结篇.html", Title: "9. 总结篇"},
	}},
	{ID: "linked-list", Label: "链表", Items: []catalogItem{
		{Path: "/链表理论基础.html", Title: "1. 链表理论基础"},
		{Path: "/0203.移除链表元素.html", Title: "2. 移除链表元素"},
		{Path: "/0707.设计链表.html", Title: "3. 设计链表"},
		{Path: "/0206.翻转链表", Title: "4. 翻转链表"},
		{Path: "/0024.两两交换链表中的节点", Title: "5. 两两交换链表中的节点"},
		{Path: "/0019.删除链表的倒数第N个节点.html", Title: "6. 删除链表的倒数第N个节点"},
		{Path: "/面试题02.07.链表相交.html", Title: "7. 链表相交"},
		{Path: "/0142.环形链表II.html", Title: "8. 环形链表II"},
		{Path: "/链表总结篇.html", Title: "9. 总结篇"},
	}},
	{ID: "hash", Label: "哈希表", Items: []catalogItem{
		{Path: "/哈希表理论基础.html", Title: "1. 哈希表理论基础"},
		{Path: "/0242.有效的字母异位词", Title: "2. 有效的字母异位词"},
		{Path: "/0349.两个数组的交集", Title: "3. 两个数组的交集"},
		{Path: "/0202.快乐数.html", Title: "4. 快乐数"},
		{Path: "/0001.两数之和.html", Title: "5. 两数之和"},
		{Path: "/0454.四数相加II.html", Title: "6. 四数相加II"},
		{Path: "/0383.赎金信.html", Title: "7. 赎金信"},
		{Path: "/0015.三数之和.html", Title: "8. 三数之和"},
		{Path: "/0018.四数之和.html", Title: "9. 四数之和"},
		{Path: "/哈希表总结.html", Title: "10. 总结篇"},
	}},
	{ID: "string", Label: "字符串", Items: []catalogItem{
		{Path: "/0344.反转字符串.html", Title: "1. 反转字符串"},
		{Path: "/0541.反转字符串II.html", Title: "2. 反转字符串II"},
		{Path: "/kamacoder/0054.替换数字.html", Title: "3. 替换数字"},
		{Path: "/0151.翻转字符串里的单词.html", Title: "4. 翻转字符串里的单词"},
		{Path: "/kamacoder/0055.右旋字符串.html", Title: "5. 右旋转字符串"},
		{Path: "/0028.实现strStr.html", Title: "6. 实现strStr())"},
		{Path: "/0459.重复的子字符串.html", Title: "7. 重复的子字符串"},
		{Path: "/字符串总结.html", Title: "8. 总结篇"},
	}},
	{ID: "two-pointers", Label: "双指针法", Items: []catalogItem{
		{Path: "/0027.移除元素.html", Title: "1. 移除元素"},
		{Path: "/0344.反转字符串.html", Title: "2. 反转字符串"},
		{Path: "/kamacoder/0054.替换数字.html", Title: "3. 替换数字"},
		{Path: "/0151.翻转字符串里的单词.html", Title: "4. 翻转字符串里的单词"},
		{Path: "/0206.翻转链表.html", Title: "5. 翻转链表"},
		{Path: "/0019.删除链表的倒数第N个节点.html", Title: "6. 删除链表的倒数第N个节点"},
		{Path: "/面试题02.07.链表相交.html", Title: "7. 链表相交"},
		{Path: "/0142.环形链表II.html", Title: "8. 环形链表II"},
		{Path: "/0015.三数之和.html", Title: "9. 三数之和"},
		{Path: "/0018.四数之和.html", Title: "10. 四数之和"},
		{Path: "/双指针总结.html", Title: "11. 双指针总结"},
	}},
	{ID: "stack-queue", Label: "栈与队列", Items: []catalogItem{
		{Path: "/栈与队列理论基础.html", Title: "1. 栈与队列理论基础"},
		{Path: "/0232.用栈实现队列.html", Title: "2. 用栈实现队列"},
		{Path: "/0225.用队列实现栈.html", Title: "3. 用队列实现栈"},
		{Path: "/0020.有效的括号.html", Title: "4. 有效的括号"},
		{Path: "/1047.删除字符串中的所有相邻重复项.html", Title: "5. 删除字符串中的所有相邻重复项"},
		{Path: "/0150.逆波兰表达式求值.html", Title: "6. 逆波兰表达式求值"},
		{Path: "/0239.滑动窗口最大值.html", Title: "7. 滑动窗口最大值"},
		{Path: "/0347.前K个高频元素.html", Title: "8. 前K个高频元素"},
		{Path: "/栈与队列总结.html", Title: "9. 栈与队列总结"},
	}},
	{ID: "binary-tree", Label: "二叉树", Items: []catalogItem{
		{Path: "/二叉树理论基础.html", Title: "1. 二叉树理论基础"},
		{Path: "/二叉树的递归遍历.html", Title: "2. 二叉树的递归遍历"},
		{Path: "/二叉树的迭代遍历.html", Title: "3. 二叉树的迭代遍历"},
		{Path: "/二叉树的统一迭代法.html", Title: "4. 二叉树的统一迭代法"},
		{Path: "/0102.二叉树的层序遍历.html", Title: "5. 二叉树的层序遍历"},
		{Path: "/0226.翻转二叉树.html", Title: "6. 翻转二叉树"},
		{Path: "/周总结/20200927二叉树周末总结.html", Title: "7. 二叉树周末总结"},
		{Path: "/0101.对称二叉树.html", Title: "8. 对称二叉树"},
		{Path: "/0104.二叉树的最大深度.html", Title: "9. 二叉树的最大深度"},
		{Path: "/0111.二叉树的最小深度.html", Title: "10. 二叉树的最小深度"},
		{Path: "/0222.完全二叉树的节点个数.html", Title: "11. 完全二叉树的节点个数"},
		{Path: "/0110.平衡二叉树.html", Title: "12. 平衡二叉树"},
		{Path: "/0257.二叉树的所有路径.html", Title: "13. 二叉树的所有路径"},
		{Path: "/周总结/20201003二叉树周末总结.html", Title: "14. 二叉树周末总结"},
		{Path: "/0404.左叶子之和.html", Title: "15. 左叶子之和"},
		{Path: "/0513.找树左下角的值.html", Title: "16. 找树左下角的值"},
		{Path: "/0112.路径总和.html", Title: "17. 路径总和"},
		{Path: "/0106.从中序与后序遍历序列构造二叉树.html", Title: "18. 从中序与后序遍历序列构造二叉树"},
		{Path: "/0654.最大二叉树.html", Title: "19. 最大二叉树"},
		{Path: "/周总结/20201010二叉树周末总结.html", Title: "20. 二叉树周末总结"},
		{Path: "/0617.合并二叉树.html", Title: "21. 合并二叉树"},
		{Path: "/0700.二叉搜索树中的搜索.html", Title: "22. 二叉搜索树中的搜索"},
		{Path: "/0098.验证二叉搜索树.html", Title: "23. 验证二叉搜索树"},
		{Path: "/0530.二叉搜索树的最小绝对差.html", Title: "24. 二叉搜索树的最小绝对差"},
		{Path: "/0501.二叉搜索树中的众数.html", Title: "25. 二叉搜索树中的众数"},
		{Path: "/0236.二叉树的最近公共祖先.html", Title: "26. 二叉树的最近公共祖先"},
		{Path: "/周总结/20201017二叉树周末总结.html", Title: "27. 二叉树周末总结"},
		{Path: "/0235.二叉搜索树的最近公共祖先.html", Title: "28. 二叉搜索树的最近公共祖先"},
		{Path: "/0701.二叉搜索树中的插入操作.html", Title: "29. 二叉搜索树中的插入操作"},
		{Path: "/0450.删除二叉搜索树中的节点.html", Title: "30. 删除二叉搜索树中的节点"},
		{Path: "/0669.修剪二叉搜索树.html", Title: "31. 修剪二叉搜索树"},
		{Path: "/0108.将有序数组转换为二叉搜索树.html", Title: "32. 将有序数组转换为二叉搜索树"},
		{Path: "/0538.把二叉搜索树转换为累加树.html", Title: "33. 把二叉搜索树转换为累加树"},
		{Path: "/二叉树总结篇.html", Title: "34. 二叉树总结篇"},
	}},
	{ID: "backtracking", Label: "回溯算法", Items: []catalogItem{
		{Path: "/回溯算法理论基础.html", Title: "1. 回溯算法理论基础"},
		{Path: "/0077.组合.html", Title: "2. 组合问题"},
		{Path: "/0077.组合优化.html", Title: "3. 组合（优化）"},
		{Path: "/0216.组合总和III.html", Title: "4. 组合总和III"},
		{Path: "/0017.电话号码的字母组合.html", Title: "5. 电话号码的字母组合"},
		{Path: "/周总结/20201030回溯周末总结.html", Title: "6. 回溯周末总结"},
		{Path: "/0039.组合总和.html", Title: "7. 组合总和"},
		{Path: "/0040.组合总和II.html", Title: "8. 组合总和II"},
		{Path: "/0131.分割回文串.html", Title: "9. 分割回文串"},
		{Path: "/0093.复原IP地址.html", Title: "10. 复原IP地址"},
		{Path: "/0078.子集.html", Title: "11. 子集问题"},
		{Path: "/周总结/20201107回溯周末总结.html", Title: "12. 回溯周末总结"},
		{Path: "/0090.子集II.html", Title: "13. 子集II"},
		{Path: "/0491.递增子序列.html", Title: "14. 递增子序列"},
		{Path: "/0046.全排列.html", Title: "15. 全排列"},
		{Path: "/0047.全排列II.html", Title: "16. 全排列II"},
		{Path: "/周总结/20201112回溯周末总结.html", Title: "17. 回溯周末总结"},
		{Path: "/回溯算法去重问题的另一种写法.html", Title: "18. 回溯算法去重问题的另一种写法"},
		{Path: "/0051.N皇后.html", Title: "20. N皇后"},
		{Path: "/0037.解数独.html", Title: "21. 解数独"},
		{Path: "/回溯总结.html", Title: "22. 回溯法总结篇"},
	}},
	{ID: "greedy", Label: "贪心算法", Items: []catalogItem{
		{Path: "/贪心算法理论基础.html", Title: "1. 贪心算法理论基础"},
		{Path: "/0455.分发饼干.html", Title: "2. 分发饼干"},
		{Path: "/0376.摆动序列.html", Title: "3. 摆动序列"},
		{Path: "/0053.最大子序和.html", Title: "4. 最大子序和"},
		{Path: "/周总结/20201126贪心周末总结.html", Title: "5. 贪心周总结"},
		{Path: "/0122.买卖股票的最佳时机II.html", Title: "6. 买卖股票的最佳时机II"},
		{Path: "/0055.跳跃游戏.html", Title: "7. 跳跃游戏"},
		{Path: "/0045.跳跃游戏II.html", Title: "8. 跳跃游戏II"},
		{Path: "/1005.K次取反后最大化的数组和.html", Title: "9. K次取反后最大化的数组和"},
		{Path: "/周总结/20201203贪心周末总结.html", Title: "10. 贪心周总结"},
		{Path: "/0134.加油站.html", Title: "11. 加油站"},
		{Path: "/0135.分发糖果.html", Title: "12. 分发糖果"},
		{Path: "/0860.柠檬水找零.html", Title: "13. 柠檬水找零"},
		{Path: "/0406.根据身高重建队列.html", Title: "14. 根据身高重建队列"},
		{Path: "/周总结/20201217贪心周末总结.html", Title: "15. 贪心周总结"},
		{Path: "/根据身高重建队列（vector原理讲解）.html", Title: "16. 根据身高重建队列（vector原理讲解）"},
		{Path: "/0452.用最少数量的箭引爆气球.html", Title: "17. 用最少数量的箭引爆气球"},
		{Path: "/0435.无重叠区间.html", Title: "18. 无重叠区间"},
		{Path: "/0763.划分字母区间.html", Title: "19. 划分字母区间"},
		{Path: "/0056.合并区间.html", Title: "20. 合并区间"},
		{Path: "/周总结/20201224贪心周末总结.html", Title: "21. 贪心周总结"},
		{Path: "/0738.单调递增的数字.html", Title: "22. 单调递增的数字"},
		{Path: "/0968.监控二叉树.html", Title: "23. 监控二叉树"},
		{Path: "/贪心算法总结篇.html", Title: "24. 贪心算法总结篇"},
	}},
	{ID: "dp", Label: "动态规划", Items: []catalogItem{
		{Path: "/动态规划理论基础.html", Title: "1. 动态规划理论基础"},
		{Path: "/0509.斐波那契数.html", Title: "2. 斐波那契数"},
		{Path: "/0070.爬楼梯.html", Title: "3. 爬楼梯"},
		{Path: "/0746.使用最小花费爬楼梯.html", Title: "4. 使用最小花费爬楼梯"},
		{Path: "/周总结/20210107动规周末总结.html", Title: "5. 动规周总结"},
		{Path: "/0062.不同路径.html", Title: "6. 不同路径"},
		{Path: "/0063.不同路径II.html", Title: "7. 不同路径II"},
		{Path: "/0343.整数拆分.html", Title: "8. 整数拆分"},
		{Path: "/0096.不同的二叉搜索树.html", Title: "9. 不同的二叉搜索树"},
		{Path: "/周总结/20210114动规周末总结.html", Title: "10. 动规周总结"},
		{Path: "/背包理论基础01背包-1.html", Title: "11. 0-1背包理论基础（一）"},
		{Path: "/背包理论基础01背包-2.html", Title: "12. 0-1背包理论基础（二）"},
		{Path: "/0416.分割等和子集.html", Title: "13. 分割等和子集"},
		{Path: "/1049.最后一块石头的重量II.html", Title: "14. 最后一块石头的重量II"},
		{Path: "/周总结/20210121动规周末总结.html", Title: "15. 动规周总结"},
		{Path: "/0494.目标和.html", Title: "16. 目标和"},
		{Path: "/0474.一和零.html", Title: "17. 一和零"},
		{Path: "/背包问题理论基础完全背包.html", Title: "18. 完全背包理论基础"},
		{Path: "/0518.零钱兑换II.html", Title: "19. 零钱兑换II"},
		{Path: "/周总结/20210128动规周末总结.html", Title: "20. 动规周总结"},
		{Path: "/0377.组合总和Ⅳ.html", Title: "21. 组合总和Ⅳ"},
		{Path: "/0070.爬楼梯完全背包版本.html", Title: "22. 爬楼梯（进阶版）"},
		{Path: "/0322.零钱兑换.html", Title: "23. 零钱兑换"},
		{Path: "/0279.完全平方数.html", Title: "24. 完全平方数"},
		{Path: "/周总结/20210204动规周末总结.html", Title: "25. 动规周总结"},
		{Path: "/0139.单词拆分.html", Title: "26. 单词拆分"},
		{Path: "/背包问题理论基础多重背包.html", Title: "27. 多重背包理论基础"},
		{Path: "/背包总结篇.html", Title: "28. 背包问题总结篇"},
		{Path: "/0198.打家劫舍.html", Title: "29. 打家劫舍"},
		{Path: "/0213.打家劫舍II.html", Title: "30. 打家劫舍II"},
		{Path: "/0337.打家劫舍III.html", Title: "31. 打家劫舍III"},
		{Path: "/0121.买卖股票的最佳时机.html", Title: "32. 买卖股票的最佳时机"},
		{Path: "/周总结/20210225动规周末总结.html", Title: "33. 动规周总结"},
		{Path: "/0122.买卖股票的最佳时机II（动态规划）.html", Title: "34. 买卖股票的最佳时机II"},
		{Path: "/0123.买卖股票的最佳时机III.html", Title: "35. 买卖股票的最佳时机III"},
		{Path: "/0188.买卖股票的最佳时机IV.html", Title: "36. 买卖股票的最佳时机IV"},
		{Path: "/0309.最佳买卖股票时机含冷冻期.html", Title: "37. 最佳买卖股票时机含冷冻期"},
		{Path: "/周总结/20210304动规周末总结.html", Title: "38. 动规周总结"},
		{Path: "/0714.买卖股票的最佳时机含手续费（动态规划）.html", Title: "39. 买卖股票的最佳时机含手续费"},
		{Path: "/动态规划-股票问题总结篇.html", Title: "40. 股票问题总结篇"},
		{Path: "/0300.最长上升子序列.html", Title: "41. 最长上升子序列"},
		{Path: "/0674.最长连续递增序列.html", Title: "42. 最长连续递增序列"},
		{Path: "/0718.最长重复子数组.html", Title: "43. 最长重复子数组"},
		{Path: "/1143.最长公共子序列.html", Title: "44. 最长公共子序列"},
		{Path: "/1035.不相交的线.html", Title: "45. 不相交的线"},
		{Path: "/0053.最大子序和（动态规划）.html", Title: "46. 最大子序和"},
		{Path: "/0392.判断子序列.html", Title: "47. 判断子序列"},
		{Path: "/0115.不同的子序列.html", Title: "48. 不同的子序列"},
		{Path: "/0583.两个字符串的删除操作.html", Title: "49. 两个字符串的删除操作"},
		{Path: "/0072.编辑距离.html", Title: "50. 编辑距离"},
		{Path: "/为了绝杀编辑距离，卡尔做了三步铺垫.html", Title: "51. 编辑距离总结篇"},
		{Path: "/0647.回文子串.html", Title: "52. 回文子串"},
		{Path: "/0516.最长回文子序列.html", Title: "53. 最长回文子序列"},
		{Path: "/动态规划总结篇.html", Title: "54. 动态规划总结篇"},
	}},
	{ID: "mono-stack", Label: "单调栈", Items: []catalogItem{
		{Path: "/0739.每日温度.html", Title: "1. 每日温度"},
		{Path: "/0496.下一个更大元素I.html", Title: "2. 下一个更大元素I"},
		{Path: "/0503.下一个更大元素II.html", Title: "3. 下一个更大元素II"},
		{Path: "/0042.接雨水.html", Title: "4. 接雨水"},
		{Path: "/0084.柱状图中最大的矩形.html", Title: "5. 柱状图中最大的矩形"},
	}},
	{ID: "graph", Label: "图论", Items: []catalogItem{
		{Path: "/about/tulunfabu.html", Title: "图论正式发布"},
		{Path: "/kamacoder/图论为什么用ACM模式.html", Title: "本章为什么用ACM模式"},
		{Path: "/kamacoder/图论理论基础.html", Title: "1. 图论理论基础"},
		{Path: "/kamacoder/图论深搜理论基础.html", Title: "2. 深度优先搜索理论基础"},
		{Path: "/kamacoder/0098.所有可达路径.html", Title: "3. 可达路径"},
		{Path: "/kamacoder/图论广搜理论基础.html", Title: "4. 广度优先搜索理论基础.md"},
		{Path: "/kamacoder/0099.岛屿的数量深搜.html", Title: "5. 岛屿问题（一）孤岛计数.深搜版"},
		{Path: "/kamacoder/0099.岛屿的数量广搜.html", Title: "6. 岛屿问题（二）孤岛计数.广搜版"},
		{Path: "/kamacoder/0100.岛屿的最大面积.html", Title: "7. 岛屿问题（三）最大岛屿的面积"},
		{Path: "/kamacoder/0101.孤岛的总面积.html", Title: "8. 岛屿问题（四）孤岛的总面积"},
		{Path: "/kamacoder/0102.沉没孤岛.html", Title: "9. 岛屿问题（五）沉没孤岛"},
		{Path: "/kamacoder/0103.水流问题.html", Title: "10. 岛屿问题（六）高山流水"},
		{Path: "/kamacoder/0104.建造最大岛屿.html", Title: "11. 岛屿问题（七）建造最大工岛"},
		{Path: "/kamacoder/0106.岛屿的周长.html", Title: "12. 岛屿问题（八）海岸线计算"},
		{Path: "/kamacoder/0110.字符串接龙.html", Title: "13. 字符串迁移"},
		{Path: "/kamacoder/0105.有向图的完全可达性.html", Title: "14. 有向图的完全连通"},
		{Path: "/kamacoder/图论并查集理论基础.html", Title: "15. 并查集理论基础"},
		{Path: "/kamacoder/0107.寻找存在的路径.html", Title: "16. 寻找存在的路线"},
		{Path: "/kamacoder/0108.冗余连接.html", Title: "17. 多余的边"},
		{Path: "/kamacoder/0109.冗余连接II.html", Title: "18. 多余的边II"},
		{Path: "/kamacoder/0053.寻宝-prim.html", Title: "19. 最小生成树之prim"},
		{Path: "/kamacoder/0053.寻宝-Kruskal.html", Title: "20. 最小生成树之Kruskal"},
		{Path: "/kamacoder/0117.软件构建.html", Title: "21. 拓扑排序"},
		{Path: "/kamacoder/0047.参会dijkstra朴素.html", Title: "22. dijkstra朴素版"},
		{Path: "/kamacoder/0047.参会dijkstra堆.html", Title: "23. dijkstra堆优化版"},
		{Path: "/kamacoder/0094.城市间货物运输I.html", Title: "24. Bellman_ford算法"},
		{Path: "/kamacoder/0094.城市间货物运输I-SPFA.html", Title: "25. Bellman_ford之队列优化"},
		{Path: "/kamacoder/0095.城市间货物运输II.html", Title: "26. Bellman_ford之判断负权回路"},
		{Path: "/kamacoder/0096.城市间货物运输III.html", Title: "27. Bellman_ford之单源有限最短路"},
		{Path: "/kamacoder/0097.小明逛公园.html", Title: "28. Floyd算法"},
		{Path: "/kamacoder/0126.骑士的攻击astar.html", Title: "29. A*算法"},
		{Path: "/kamacoder/最短路问题总结篇.html", Title: "30. 最短路问题总结篇"},
		{Path: "/kamacoder/图论总结篇.html", Title: "31. 图论总结篇"},
	}},
	{ID: "extra", Label: "额外题目", Items: []catalogItem{
		{Path: "/qita/ewaishuoming.html", Title: "本模块说明"},
		{Path: "/1365.有多少小于当前数字的数字.html", Title: "数组：有多少小于当前数字的数字"},
		{Path: "/0941.有效的山脉数组.html", Title: "数组：有效的山脉数组"},
		{Path: "/1207.独一无二的出现次数.html", Title: "数组：独一无二的出现次数"},
		{Path: "/0283.移动零.html", Title: "数组：移动零"},
		{Path: "/0189.旋转数组.html", Title: "数组：旋转数组"},
		{Path: "/0724.寻找数组的中心索引.html", Title: "数组：寻找数组的中心索引"},
		{Path: "/0034.在排序数组中查找元素的第一个和最后一个位置.html", Title: "数组：在排序数组中查找元素的第一个和最后一个位置"},
		{Path: "/0922.按奇偶排序数组II.html", Title: "数组：按奇偶排序数组II"},
		{Path: "/0035.搜索插入位置.html", Title: "数组：搜索插入位置"},
		{Path: "/0024.两两交换链表中的节点", Title: "链表：两两交换链表中的节点"},
		{Path: "/0234.回文链表.html", Title: "链表：回文链表"},
		{Path: "/0143.重排链表.html", Title: "链表：重排链表"},
		{Path: "/0141.环形链表.html", Title: "链表：环形链表"},
		{Path: "/0160.相交链表.html", Title: "链表：相交链表"},
		{Path: "/0205.同构字符串.html", Title: "哈希表：同构字符串"},
		{Path: "/1002.查找常用字符.html", Title: "哈希表：查找常用字符"},
		{Path: "/0925.长按键入.html", Title: "字符串：长按键入"},
		{Path: "/0844.比较含退格的字符串.html", Title: "字符串：比较含退格的字符串"},
		{Path: "/0129.求根到叶子节点数字之和.html", Title: "二叉树：求根到叶子节点数字之和"},
		{Path: "/1382.将二叉搜索树变平衡.html", Title: "二叉树：将二叉搜索树变平衡"},
		{Path: "/0100.相同的树.html", Title: "二叉树：相同的树"},
		{Path: "/0116.填充每个节点的下一个右侧节点指针.html", Title: "二叉树：填充每个节点的下一个右侧节点指针"},
		{Path: "/0052.N皇后II.html", Title: "回溯算法：N皇后II"},
		{Path: "/0649.Dota2参议院.html", Title: "贪心：Dota2参议院"},
		{Path: "/1221.分割平衡字符串.html", Title: "贪心：分割平衡字符串"},
		{Path: "/0005.最长回文子串.html", Title: "动态规划：最长回文子串"},
		{Path: "/0132.分割回文串II.html", Title: "动态规划：分割回文串II"},
		{Path: "/0673.最长递增子序列的个数.html", Title: "动态规划：最长递增子序列的个数"},
		{Path: "/0841.钥匙和房间.html", Title: "图论：钥匙和房间"},
		{Path: "/0127.单词接龙.html", Title: "图论：单词接龙"},
		{Path: "/0684.冗余连接.html", Title: "并查集：冗余连接"},
		{Path: "/0685.冗余连接II.html", Title: "并查集：冗余连接II"},
		{Path: "/0657.机器人能否返回原点.html", Title: "模拟：机器人能否返回原点"},
		{Path: "/0031.下一个排列.html", Title: "模拟：下一个排列"},
		{Path: "/0463.岛屿的周长.html", Title: "模拟：岛屿的周长"},
		{Path: "/1356.根据数字二进制下1的数目排序.html", Title: "位运算：根据数字二进制下1的数目排序"},
	}},
	{ID: "feeling", Label: "感悟", Items: []catalogItem{
		{Path: "/qita/say_feel.html", Title: "通关代码随想录"},
	}},
}

var catalogByID = map[string]*catalogSection{}

func init() {
	for i := range catalogSections {
		catalogByID[catalogSections[i].ID] = &catalogSections[i]
	}
}
